---
- name: Get dynamic inventory
  hosts: localhost
  become: false
  gather_facts: true
  collections:
    - kubernetes.core
    - community.aws
    - ansible.utils
    - community.general
    
  tasks:
  - name: Get volumes in a namespace and record the values
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Node
    register: nodes
  
  - name: Debug
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ nodes | community.general.json_query('resources[*].metadata.name') }}"
