---
- name: Get dynamic inventory
  hosts: localhost
  become: false
  gather_facts: true
  collections:
    - kubernetes.core
    - community.aws
    - ansible.utils
    - community.general
    
  tasks:
  - name: Get nodes
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Node
    register: nodes

  - name: flatten nodes object
    ansible.builtin.set_fact:
      paths: "{{ lookup('ansible.utils.to_paths', nodes) }}"

  - name: flatten debug
    ansible.builtin.debug:
      var: paths
  
  - name: Debug
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ nodes | community.general.json_query('resources[*].metadata.name') }}"
