---
- name: Backup
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
    - community.aws
    - ansible.utils
    - community.general
    
  tasks:
  - name: list volumes in a namespace and record the values
    kubernetes.core.k8s_info:
      api_version: v1
      kind: PersistentVolumeClaim
      namespace: "{{ my_namespace }}"
    register: pvc
    
  - name: Get the default VolumeSnapshotClass
    kubernetes.core.k8s_info:
      apiversion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshotClass
    register: volumesnapshotclass
    
  - name: flatten pvc object
    ansible.builtin.set_fact:
      pvc_paths: "{{ lookup('ansible.utils.to_paths', pvc) }}"

  - name: Debug pvc path
     ansible.builtin.debug:
     var: pvc_paths
     
  - name: flatten volumesnapshotclass object
    ansible.builtin.set_fact:
      volumesnapshotclass_paths: "{{ lookup('ansible.utils.to_paths', volumesnapshotclass) }}"
 
   - name: Debug volumesnapshotclass path
     ansible.builtin.debug:
     var: volumesnapshotclass_paths
